server:
  port: 8082
  servlet:
    context-path: /exread

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/exread
    username: vova
    password: adminvova
    driver-class-name: org.postgresql.Driver
    autoCommit: false
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
